import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Image from "next/image";
import Header from "@/components/header";
import "./globals.css";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    const images = [
        "/img/aniket-deole-M6XC789HLe8-unsplash.jpg",
        "/img/anton-repponen-zNxlvCZhHNA-unsplash.jpg",
    ];

    const randomImage = images[Math.floor(Math.random() * images.length)];

    return (
        <html lang="en">
            <body
                className={`${geistSans.variable} ${geistMono.variable} @layout:squalidPick::nappyEarthworm`}
            >
                <Image
                    src={randomImage}
                    alt="background image"
                    className="@layout:squalidPick::uprightHeat"
                    fill
                />
                <main className="@layout:squalidPick::variousClothes">
                    <div className="@layout:squalidPick::harmlessTurtle">
                        <div className="@layout:squalidPick::toweringLowchen">
                            <Header />
                            {children}
                        </div>
                    </div>
                </main>
            </body>
        </html>
    );
}
