name: Build with Webpack and Galadriel CSS

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Cache Galadriel CSS binary
      uses: actions/cache@v2
      with:
        path: .galadrielcss
        key: ${{ runner.os }}-galadrielcss-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-galadrielcss-

    - name: Install dependencies
      run: npm install

    - name: Install Galadriel CSS if not cached
      run: |
        if [ ! -f ".galadrielcss/bin/galadrielcss" ]; then
          echo "Galadriel CSS binary not found, downloading...";
          curl -L -o .galadrielcss/bin/galadrielcss https://github.com/patrickgunnar/galadrielcss/releases/latest/download/galadrielcss-linux-x86_64
          chmod +x .galadrielcss/bin/galadrielcss
        fi

    - name: Run Webpack build
      run: npm run build
